import { BusinessCategory } from "@/app/models/supabase.models";

export const categoryBackgrounds: Record<BusinessCategory, string> = {
    hair_salon: 'bg-amber-900/10',
    nail_salon: 'bg-pink-900/10',
    waxing_salon: 'bg-purple-900/10',
    beauty_salon: 'bg-rose-900/10',
    barbershop: 'bg-orange-900/10',
    eyebrows_and_lashes: 'bg-fuchsia-900/10',
    massage: 'bg-violet-900/10',
    spa: 'bg-emerald-900/10',
    gym_and_fitness: 'bg-neutral-900/10',
    personal_trainer: 'bg-slate-900/10',
    therapy_centre: 'bg-teal-900/10',
    tattoo_and_piercing: 'bg-zinc-900/10',
    tanning_studio: 'bg-amber-800/10',
    aesthetics: 'bg-indigo-900/10',
    weight_loss: 'bg-cyan-900/10',
    yoga_studio: 'bg-green-900/10',
    pilates_studio: 'bg-lime-900/10',
    dental_clinic: 'bg-blue-900/10',
    chiropractor: 'bg-sky-900/10',
    physiotherapy: 'bg-red-900/10',
    acupuncture: 'bg-yellow-900/10',
    meditation_centre: 'bg-purple-800/10',
    wellness_centre: 'bg-emerald-800/10',
    makeup_artist: 'bg-pink-800/10',
    hair_removal: 'bg-rose-800/10'
  };
  
  export const categoryBorders: Record<BusinessCategory, string> = {
    hair_salon: 'border-amber-900',
    nail_salon: 'border-pink-900',
    waxing_salon: 'border-purple-900',
    beauty_salon: 'border-rose-900',
    barbershop: 'border-orange-900',
    eyebrows_and_lashes: 'border-fuchsia-900',
    massage: 'border-violet-900',
    spa: 'border-emerald-900',
    gym_and_fitness: 'border-neutral-900',
    personal_trainer: 'border-slate-900',
    therapy_centre: 'border-teal-900',
    tattoo_and_piercing: 'border-zinc-900',
    tanning_studio: 'border-amber-800',
    aesthetics: 'border-indigo-900',
    weight_loss: 'border-cyan-900',
    yoga_studio: 'border-green-900',
    pilates_studio: 'border-lime-900',
    dental_clinic: 'border-blue-900',
    chiropractor: 'border-sky-900',
    physiotherapy: 'border-red-900',
    acupuncture: 'border-yellow-900',
    meditation_centre: 'border-purple-800',
    wellness_centre: 'border-emerald-800',
    makeup_artist: 'border-pink-800',
    hair_removal: 'border-rose-800'
  };